// Generated by CoffeeScript 1.10.0
(function() {
  var circleImageDefaultColor, drawCircleOnCircleImage, easyimg, fs, onErr, parallel, pinOffline, pinOnline, thumbnails, toDisk, waterfall;

  waterfall = require('async').waterfall;

  parallel = require('async').parallel;

  easyimg = require('easyimage');

  fs = require('fs');

  onErr = function(err) {
    return console.log(err);
  };

  toDisk = function(callback) {
    return callback(null, {
      originalFilePath: '/home/ryuk/lfreneda/work/others/playing-with-images/mad.jpg'
    });
  };

  thumbnails = function(options, callback) {
    var destinationFilePath, onOk;
    destinationFilePath = __dirname + '/output/mad_thumbnail.jpg';
    onOk = function() {
      options.thumbnailFilePath = destinationFilePath;
      return callback(null, options);
    };
    return easyimg.thumbnail({
      src: options.originalFilePath,
      dst: destinationFilePath,
      width: 200,
      height: 200
    }).then(onOk, onErr);
  };

  circleImageDefaultColor = function(options, callback) {
    var command, destinationFilePath, onOk;
    destinationFilePath = __dirname + '/output/mad_thumbnail-circle.png';
    command = 'convert -size 200x200 xc:none -fill ' + options.thumbnailFilePath + ' -draw "circle 100,100 100,1" ' + destinationFilePath;
    onOk = function() {
      options.thumbnailCircleFilePath = destinationFilePath;
      return callback(null, options);
    };
    return easyimg.exec(command).then(onOk, onErr);
  };

  drawCircleOnCircleImage = function(options, callback) {
    var command, destinationFilePath;
    destinationFilePath = __dirname + '/output/mad_thumbnail-circle-offline-aaaaaaaa.png';
    command = 'convert -size 200x200 xc:none ' + options.thumbnailCircleFilePath + ' -draw "circle 80,60 120,30" xc:black ' + destinationFilePath;
    console.log(command);
    return easyimg.exec(command).then(function() {
      options.thumbnailCircleOfflineFilePath = destinationFilePath;
      return callback(null, options);
    });
  };

  pinOnline = function(options, callback) {
    var destinationFilePath, onOk;
    destinationFilePath = __dirname + '/output/pin-online.png';
    onOk = function() {
      options.thumbnailPinCircleOnlineFilePath = destinationFilePath;
      return callback(null, options);
    };
    return easyimg.thumbnail({
      src: '/home/ryuk/lfreneda/work/others/playing-with-images/c.png',
      dst: destinationFilePath,
      width: 32,
      height: 32
    }).then(onOk, onErr);
  };

  pinOffline = function(options, callback) {
    var destinationFilePath, onOk;
    destinationFilePath = __dirname + '/output/pin-offline.png';
    onOk = function() {
      options.thumbnailPinCircleOfflineFilePath = destinationFilePath;
      return callback(null, options);
    };
    return easyimg.thumbnail({
      src: '/home/ryuk/lfreneda/work/others/playing-with-images/d.png',
      dst: destinationFilePath,
      width: 32,
      height: 32
    }).then(onOk, onErr);
  };

  waterfall([toDisk, pinOnline, pinOffline], function(err, result) {
    if (err) {
      return console.log(err);
    } else {
      return console.log(JSON.stringify(result.output));
    }
  });

}).call(this);

//# sourceMappingURL=flow.js.map
